# Generated by Django 5.1.3 on 2024-11-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klines',
            name='number_trades',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='klines',
            name='quote_volume',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='klines',
            name='taker_buy_base_volume',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='klines',
            name='taker_buy_quote_volume',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='klines',
            name='volume',
            field=models.FloatField(),
        ),
    ]
