# Generated by Django 5.1.3 on 2024-11-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klines', '0002_alter_klines_number_trades_alter_klines_quote_volume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klines',
            old_name='number_trades',
            new_name='number_of_trades',
        ),
        migrations.RenameField(
            model_name='klines',
            old_name='quote_volume',
            new_name='quote_asset_volume',
        ),
        migrations.RenameField(
            model_name='klines',
            old_name='taker_buy_base_volume',
            new_name='taker_buy_base_asset_volume',
        ),
        migrations.RenameField(
            model_name='klines',
            old_name='taker_buy_quote_volume',
            new_name='taker_buy_quote_asset_volume',
        ),
    ]
